Pagenation issues
planetlabs/notebooks pull request #267
Opened 2023-05-10 21:20 UTC by emma-steuer

2023-05-24 19:39 UTC, sgillies commented
@joferkington as the reporter of the issue and the one with the most basemaps experience, can you review this?

2023-05-25 21:38 UTC, joferkington commented on jupyter-notebooks/orders_basemaps/SDK_order_basemaps.ipynb
> +    "It is only possible to place orders with 100 quad IDs at a time. This function will batch the quad IDs into lists of 100 each and place each of those orders. "
Isn't it 50 if merge is used?  Or did that get increased to 100?

2023-05-25 21:48 UTC, joferkington approved these changes
Thanks for this, and it's a definite improvement!!  The pagination is quite important and this fixes the issue there, as well as being an improvement overall.

My one comment is that we're showing the polygon search in the orders API sections and not the general basemaps API sections.  I wonder if it might make sense to demonstrate ordering a basemap by AOI directly in the orders section and have the polygon search portions in the basemaps API demos?

If you're using the orders API, at least for small AOIs, it's easiest to submit the polygon directly instead of using the basemaps API to do the search for quad IDs.  E.g. you can submit an order similar to this:

```
   order = {
        "description": "foobar",
        "source_type": "basemaps",
        "order_type": "partial",
        "products": [
            {
                "mosaic_name": <mosaic_name>,
                "geometry": <direct_geojson_polygon>,
            }
        ],
        "tools": []
    }
```

However, that will fail if too many quads are in the polygon.  

The approach you have here of searching for the quads explicitly and then chunking orders up into N quads works around that and is a _very_ useful thing to demonstrate, as it's frequently needed.

It's a good thing to demonstrate, but I also wonder if it's too much complexity to show in a basic example?  I honestly don't know, though, and it's _definitely_ useful to show these sort of chunking approaches.  

At any rate, I defer to you on that. What you have currently is _great_! I think it's fine to merge as is. My comment was mostly me thinking out loud, and feel free to ignore it!

2023-05-30 18:28 UTC, kevinlacaille requested changes
Great improvement! 

I still need to take a look at why the last cell containing `await batch_lists_and_place_orders(quad_ids, polygon_search_order_params)` is rendering >20 lines between reports. I replaced the callback function with simply `print()` and it's still doing the same thing. I'll have to dive deeper into this. 

In the mean time, just check out my comments!

2023-05-30 18:48 UTC, kevinlacaille commented on jupyter-notebooks/orders_basemaps/SDK_order_basemaps.ipynb
> +    "    session.auth = (api_key, '')\n",
Oh, and you can get rid of `api_key` in your inputs and docstring :)

2023-05-31 17:40 UTC, kevinlacaille requested changes
A few more little things!

2023-05-31 21:06 UTC, kevinlacaille requested changes

2023-05-31 21:06 UTC, kevinlacaille commented on jupyter-notebooks/orders_basemaps/SDK_order_basemaps.ipynb
>     "source": [
If you do get rid of it, then you may remove `HTTPBasicAuth` from imports.

2023-05-31 21:08 UTC, kevinlacaille commented on jupyter-notebooks/orders_basemaps/SDK_order_basemaps.ipynb
> +    "async def batch_lists_and_place_orders(quad_ids, order_params):\n",
The formatting looks weird on this function. Try as I noted in Slack, like this

```python
async def batch_lists_and_place_orders(quad_ids, order_params):
    """
    Process quad IDs in batches and create orders.

    Parameters:
        quad_ids (list): A list of quad IDs to be processed in batches.
        order_params (dict): The order parameters dictionary that contains the details of the order.

    """

    # Calculate the number of batches
    num_batches = math.ceil(len(quad_ids) / 100)

    # Create batched quad IDs lists
    batched_quad_ids = [
        quad_ids[i:i + 100] for i in range(0, len(quad_ids), 100)
    ]

    # Duplicate the order_params dictionary for each batch
    all_order_params = [
        copy.deepcopy(order_params) for _ in range(num_batches)
    ]

    # Assign batched quad IDs to each order_params dictionary
    for i, params in enumerate(all_order_params):
        params['products'][0]['quad_ids'] = batched_quad_ids[i]

    async with planet.Session() as ps:
        # The Orders API client
        client = ps.client('orders')

        # Create the order and deliver it to GCP for each batch
        await asyncio.gather(*[
            create_and_deliver_order(params, client)
            for params in all_order_params
        ])
```

2023-06-01 17:55 UTC, kevinlacaille requested changes
A few more things.

Also, I can't comment on the function itself, but `poll_for_success()` no longer needs `num_loops` in its docstring.

2023-06-01 17:55 UTC, kevinlacaille commented on jupyter-notebooks/orders_basemaps/requests_order_basemaps.ipynb
> +    "poll_for_success(order_url)"
I think I'm confused what's supposed to be happening here. Why do we poll in this cell and the cell above? Do we need both?

2023-06-01 17:55 UTC, kevinlacaille commented on jupyter-notebooks/orders_basemaps/SDK_order_basemaps.ipynb
> +    "from urllib3.util.retry import Retry\n",
Get rid of either this one or the one below, please.

2023-06-02 17:13 UTC, kevinlacaille approved these changes
This is a huge improvement, Emma! Great work 💪

2023-06-02 17:24 UTC, merged